### ISSUE TITLE
Softphone connection.

### ISSUE THREAD

**Issue by ismail-codar** [chadxz/asterisk-playground#9]
Hi @chadxz asterisk-playground looks very helpfull but I am very new to asterisk. I want to connect with a softhone (http://www.counterpath.com/x-lite/) 

Here is my acount settings screenshot but it fails. Can you help me for correct settings. 

Note: Currently I can access system. (For example: http://192.168.68.68:8088/ari/api-docs/resources.json is working)

![image](https://user-images.githubusercontent.com/282104/35781814-04a53b22-0a00-11e8-8223-4f28b139ef95.png)

**Comment by chadxz** [comment]
Are you able to register, but aren't hearing sound?

**Comment by chadxz** [comment]
Remove the http from your account and try that

**Comment by ismail-codar** [comment]
Thanks @chadxz username: 6001 password:password and domain: 192.168.68.68  is worked.

**Comment by chadxz** [comment]
cool. LMK if you have any other questions
